#! /bin/sh

sxhkd &
numlockx                                                   # numlock on
KeeWeb &                                                   # password
nm-applet --sm-disable &                                   # Network Manager
insync &                                                   # Insync
/usr/bin/gnome-keyring-daemon --start --components=secrets # for chrome
xfce4-power-manager                                        # brightnes
xset dpms 600                                              # turn off screen
# dropbox start -i                                           # Dropbox
# nm-applet --sm-disable &                                   # Network Manager


# bspc monitor -d I II III IV V VI VII
xrandr --output eDP-1-1 --off # close laptop screen
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc monitor DP-1-2 -d I II III IV V VI VII
bspc monitor eDP-1-1 -d VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#open Funny Java Things
bspc config focus_follows_pointer false
wmname LG3D

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
bspc rule -a Alacritty:fzf-dmenu state=floating
bspc rule -a KeeWeb state=floating
bspc rule -a Insync state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
