#!/bin/bash

# RC files

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
  curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi

BASE=$(pwd)
for rc in *rc tmux.conf alacritty.yml; do
  mkdir -pv bak
  [ -e ~/."$rc" ] && mv -v ~/."$rc" bak/."$rc"
  ln -sfv "$BASE/$rc" ~/."$rc"
done
source ~/.bashrc

git config --global user.email "jkunlin@gmail.com"
git config --global user.name "jkunlin"

if [ ! -e ~/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  tmux source-file ~/.tmux.conf
fi


# install softwares
#######################################################################
[ ! -e ~/bin ] && mkdir -p ~/bin
[ ! -e ~/.local ] && mkdir -p ~/.local
[ ! -e ~/.local/bin ] && mkdir ~/.local/bin
[ ! -e ~/.local/include  ] && mkdir ~/.local/include
[ ! -e ~/.local/lib ] && mkdir ~/.local/lib
[ ! -e ~/.local/libexec ] && mkdir ~/.local/libexec
[ ! -e ~/.local/share ] && mkdir ~/.local/share

mkdir -p $BASE/tmp

# fd
if ! command -v fd 2>/dev/null; then
  curl --insecure -fLo $BASE/tmp/fd_7.3.0_amd64.deb https://github.com/sharkdp/fd/releases/download/v7.3.0/fd_7.3.0_amd64.deb
  dpkg -x $BASE/tmp/fd_7.3.0_amd64.deb $BASE/tmp
  cp $BASE/tmp/usr/bin/fd ~/.local/bin
fi

# rg
if ! command -v rg 2>/dev/null; then
  curl --insecure -fLo $BASE/tmp/ripgrep_0.10.0_amd64.deb https://github.com/BurntSushi/ripgrep/releases/download/0.10.0/ripgrep_0.10.0_amd64.deb
  dpkg -x $BASE/tmp/ripgrep_0.10.0_amd64.deb $BASE/tmp
  cp $BASE/tmp/usr/bin/rg ~/.local/bin
fi

# parallel
if ! command -v parallel 2>/dev/null; then
  cd $BASE/tmp
  wget -c https://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2
  tar xjf parallel-latest.tar.bz2
  cd  $(fd --maxdepth 1 parallel -t d)
  ./configure --prefix=$HOME/.local
  make -j
  make install
  cd ../..
fi

rm -r $BASE/tmp

# neovim
./vim/install-vim
