#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1


sudo apt install libxcb1-dev libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev libxcb-icccm4-dev libyajl-dev libstartup-notification0-dev libxcb-randr0-dev libev-dev libxcb-cursor-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev xutils-dev libxcb-shape0-dev autoconf

sudo apt install numlockx

BASE=$(pwd)
mkdir -p $BASE/tmp

# conky
cd "$BASE/tmp" || exit 1
if ! command -v conky 2>/dev/null; then
  curl -sL -o conky-x86_64.AppImage \
      $(curl -sL https://api.github.com/repos/brndnmtthws/conky/releases/latest | \
      jq --raw-output '.assets[0] | .browser_download_url')
  mv conky-x86_64.AppImage $HOME/.local/bin/conky
  chmod a+x $HOME/.local/bin/conky
fi

# xcb-util-xrm
cd $BASE/tmp || exit 1
git clone https://github.com/Airblader/xcb-util-xrm
cd xcb-util-xrm
git submodule update --init
./autogen.sh --prefix=/usr
make -j
sudo make install

# i3-gaps
cd $BASE/tmp || exit 1
git clone https://www.github.com/Airblader/i3 i3-gaps
cd i3-gaps || exit 1
autoreconf --force --install
mkdir build
cd build || exit 1
../configure --prefix=/usr --sysconfdir=/etc
make -j
sudo make install

# RC
if [ ! -e $HOME/.config/i3 ]; then
  mkdir -p $HOME/.config/i3
fi

cd $BASE || exit 1
ln -sfv "$BASE/i3_config" ~/.config/i3/config
ln -sfv "$BASE/jconky" ~/.config/i3/jconky
ln -sfv "$BASE/conkyrc" ~/.config/i3/conkyrc

# touchpad
sudo mkdir -p /etc/X11/xorg.conf.d && sudo tee <<'EOF' /etc/X11/xorg.conf.d/90-touchpad.conf 1> /dev/null
Section "InputClass"
        Identifier "touchpad"
        MatchIsTouchpad "on"
        Driver "libinput"
        Option "Tapping" "on"
        Option "NaturalScrolling" "true"
EndSection

EOF

# brightness
sudo apt install xfce4-power-manager
