#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

sudo apt-get install libxcb-xinerama0-dev libxcb-icccm4-dev libxcb-randr0-dev libxcb-util0-dev libxcb-ewmh-dev libxcb-keysyms1-dev libxcb-shape0-dev

sudo apt install numlockx

BASE=$(pwd)
mkdir -p $BASE/tmp

# bspwm and sxhkd
# cd $BASE/tmp || exit 1
# git clone https://github.com/baskerville/bspwm.git
# git clone https://github.com/baskerville/sxhkd.git
# cd bspwm && make && sudo make install
# cd ../sxhkd && make && sudo make install
#
# mkdir -p ~/.config/{bspwm,sxhkd}
# cp /usr/local/share/doc/bspwm/examples/bspwmrc ~/.config/bspwm/
# cp /usr/local/share/doc/bspwm/examples/sxhkdrc ~/.config/sxhkd/
# chmod u+x ~/.config/bspwm/bspwmrc

# polybar

## build dependence
sudo apt install build-essential git cmake cmake-data pkg-config python3
pip3 install --user sphinx

## dependence
sudo apt install build-essential git cmake cmake-data pkg-config python3-sphinx libcairo2-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-composite0-dev python-xcbgen xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev

## optional dependence
sudo apt install libxcb-xkb-dev  libxcb-cursor-dev libasound2-dev libpulse-dev libjsoncpp-dev libmpdclient-dev libcurl4-openssl-dev libnl-genl-3-dev
sudo apt install libxcb-xrm-dev

# sudo apt install build-essential git cmake cmake-data pkg-config libcairo2-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-composite0-dev python-xcbgen xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev xbacklight

## install
cd $BASE/tmp || exit 1
wget https://github.com/polybar/polybar/releases/download/3.4.1/polybar-3.4.1.tar
tar xvf polybar-3.4.1.tar
cd polybar/ 
mkdir build 
cd build/ 
cmake .. 
make -j 
sudo make install
install -Dm644 /usr/local/share/doc/polybar/config $HOME/.config/polybar/config

exit 0

pip3 install --user i3-workspace-names-daemon

# conky
cd "$BASE/tmp" || exit 1
if ! command -v conky 2>/dev/null; then
  curl -sL -o conky-x86_64.AppImage \
      $(curl -sL https://api.github.com/repos/brndnmtthws/conky/releases/latest | \
      jq --raw-output '.assets[0] | .browser_download_url')
  mv conky-x86_64.AppImage $HOME/.local/bin/conky
  chmod a+x $HOME/.local/bin/conky
fi

# xcb-util-xrm
cd $BASE/tmp || exit 1
git clone https://github.com/Airblader/xcb-util-xrm
cd xcb-util-xrm
git submodule update --init
./autogen.sh --prefix=/usr
make -j
sudo make install

# i3-gaps
cd $BASE/tmp || exit 1
git clone https://www.github.com/Airblader/i3 i3-gaps
cd i3-gaps || exit 1
autoreconf --force --install
mkdir build
cd build || exit 1
../configure --prefix=/usr --sysconfdir=/etc
make -j
sudo make install

# RC
if [ ! -e $HOME/.config/i3 ]; then
  mkdir -p $HOME/.config/i3
fi

cd $BASE || exit 1
ln -sfv "$BASE/i3_config" ~/.config/i3/config
ln -sfv "$BASE/jconky" ~/.config/i3/jconky
ln -sfv "$BASE/conkyrc" ~/.config/i3/conkyrc
ln -sfv "$BASE/i3-app-icons.json" ~/.config/i3/app-icons.json
ln -sfv "$BASE/passmenu" ~/.local/bin/passmenu & chmod a+x ~/.local/bin/passmenu

# touchpad
sudo mkdir -p /etc/X11/xorg.conf.d && sudo tee <<'EOF' /etc/X11/xorg.conf.d/90-touchpad.conf 1> /dev/null
Section "InputClass"
        Identifier "touchpad"
        MatchIsTouchpad "on"
        Driver "libinput"
        Option "Tapping" "on"
        Option "NaturalScrolling" "true"
EndSection

EOF

# brightness
sudo apt install xfce4-power-manager
