#!/bin/bash
[ ! -e ~/bin ] && mkdir -p ~/bin
[ ! -e ~/.local ] && mkdir -p ~/.local
source ~/.bashrc

BASE=$(pwd)
mkdir -p $BASE/tmp

# llvm + clang
if [ ! -e ~/.local/clangd/bin/clangd ]; then
	cd $BASE/tmp
  wget -c https://github.com/clangd/clangd/releases/download/13.0.0/clangd-linux-13.0.0.zip
  unzip clangd-linux-13.0.0.zip
  mv clangd_13.0.0 ~/.local/clangd
fi

# rm -rf $BASE/tmp
