#!/bin/bash

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

# vimrc
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sf $BASE/vimrc ~/.vimrc
ln -sf $BASE/mysnippets ~/.vim/
ln -sf $BASE/vale.ini ~/.vim/.vale.ini
ln -sf $BASE/ycm_extra_conf.py ~/.vim/.ycm_extra_conf

# nvim
curl --insecure -fLo ~/bin/nvim https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
chmod u+x ~/bin/nvim
mkdir -p ~/.config/nvim/autoload
ln -sf $BASE/vimrc ~/.config/nvim/init.vim
ln -sf ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/

# provider-python
pip2 install --user --upgrade neovim
pip3 install neovim-remote

~/bin/nvim +PlugInstall +qall
