#!/bin/bash
[ ! -e ~/bin ] && mkdir -p ~/bin
[ ! -e ~/.local ] && mkdir -p ~/.local
source ~/.bashrc

BASE=$(pwd)
mkdir -p $BASE/tmp

# llvm + clang
if [ ! -e ~/.local/clang_llvm/bin/clang ]; then
	cd $BASE/tmp
  wget -c http://releases.llvm.org/9.0.0/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz 
  tar xf clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz 
  mv clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04 ~/.local/clang_llvm
fi

# rm -rf $BASE/tmp
