#!/bin/bash
[ ! -e ~/bin ] && mkdir -p ~/bin
[ ! -e ~/.local ] && mkdir -p ~/.local
source ~/.bashrc

BASE=$(pwd)
mkdir -p $BASE/tmp

# llvm + clang
if [ ! -e ~/.local/clang_llvm/bin/clang ]; then
	cd $BASE/tmp
  wget -c https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.1/clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz
  tar xf clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz
  mv clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04 ~/.local/clang_llvm
fi

# rm -rf $BASE/tmp
