#! /bin/sh
gap=5

# This create negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges
bspc config window_gap $gap
bspc config left_padding -$gap
bspc config right_padding -$gap

bspc config border_width         1

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#open Funny Java Things
bspc config focus_follows_pointer false
wmname LG3D

bspc monitor -d I II III IV V VI VII
# bspc monitor DP-1-2 -d I II III IV V VI VII
# bspc monitor eDP-1-1 -d VIII IX X
# xrandr --output eDP-1-1 --off # close laptop screen
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
bspc rule -a Alacritty:fzf-dmenu state=floating
bspc rule -a KeeWeb state=floating
bspc rule -a Insync state=floating
bspc rule -a flameshot state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

sxhkd &
numlockx                                                   # numlock on
KeeWeb &                                                   # password
nm-applet --sm-disable &                                   # Network Manager
insync &                                                   # Insync
/usr/bin/gnome-keyring-daemon --start --components=secrets # for chrome
xfce4-power-manager                                        # brightnes
xset dpms 600                                              # turn off screen
flameshot &                                                # screenshot
# dropbox start -i                                           # Dropbox
# nm-applet --sm-disable &                                   # Network Manager
$HOME/.config/polybar/launch.sh
