#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1



BASE=$(pwd)
mkdir -p $BASE/tmp


# ----------------------------------------------------------------------------
# bspwm and sxhkd
# ----------------------------------------------------------------------------
# sudo apt-get install libxcb-xinerama0-dev libxcb-icccm4-dev libxcb-randr0-dev libxcb-util0-dev libxcb-ewmh-dev libxcb-keysyms1-dev libxcb-shape0-dev
# cd $BASE/tmp || exit 1
# git clone https://github.com/baskerville/bspwm.git
# git clone https://github.com/baskerville/sxhkd.git
# cd bspwm && make && sudo make install
# cd ../sxhkd && make && sudo make install
#
# mkdir -p ~/.config/{bspwm,sxhkd}
# cp /usr/local/share/doc/bspwm/examples/bspwmrc ~/.config/bspwm/
# cp /usr/local/share/doc/bspwm/examples/sxhkdrc ~/.config/sxhkd/
# chmod u+x ~/.config/bspwm/bspwmrc

# ----------------------------------------------------------------------------
# polybar
# ----------------------------------------------------------------------------
## build dependence
sudo apt install build-essential git cmake cmake-data pkg-config python3
pip3 install --user sphinx

## dependence
sudo apt install build-essential git cmake cmake-data pkg-config python3-sphinx libcairo2-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-composite0-dev python-xcbgen xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev

## optional dependence
sudo apt install libxcb-xkb-dev  libxcb-cursor-dev libasound2-dev libpulse-dev libjsoncpp-dev libmpdclient-dev libcurl4-openssl-dev libnl-genl-3-dev
sudo apt install libxcb-xrm-dev

## install
cd $BASE/tmp || exit 1
wget https://github.com/polybar/polybar/releases/download/3.4.1/polybar-3.4.1.tar
tar xvf polybar-3.4.1.tar
cd polybar/ 
mkdir build 
cd build/ 
cmake .. 
make -j 
sudo make install
install -Dm644 /usr/local/share/doc/polybar/config $HOME/.config/polybar/config

exit 0

# touchpad
sudo mkdir -p /etc/X11/xorg.conf.d && sudo tee <<'EOF' /etc/X11/xorg.conf.d/90-touchpad.conf 1> /dev/null
Section "InputClass"
        Identifier "touchpad"
        MatchIsTouchpad "on"
        Driver "libinput"
        Option "Tapping" "on"
        Option "NaturalScrolling" "true"
EndSection

EOF

# brightness
sudo apt install xfce4-power-manager

# open numlock
sudo apt install numlockx
